# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(A) âš’ Mac build"

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: true
      pgo:
        type: boolean
        required: true

  workflow_call:
    inputs:
      debug:
        type: boolean
        required: true
      pgo:
        type: boolean
        required: true

run-name: ${{toJSON(inputs.pgo) == 'true' && '[PGO] ' || ''}}Mac x64 build${{toJSON(inputs.debug) == 'true' && ' Debug' || ''}}
jobs:
  get-buildid:
    runs-on: ubuntu-latest
    outputs:
      buildids: ${{ steps.get.outputs.bid }}
    steps:
      - id: get
        shell: bash -xe {0}
        run: |
          bdat=`date +"%Y%m%d%I%M%S"`
          echo "bid=${bdat}" >> $GITHUB_OUTPUT

  part1:
    needs: [get-buildid]
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      arch: x86_64
      debug: ${{ inputs.debug }}
      MOZ_BUILD_DATE: ${{ needs.get-buildid.outputs.buildids }}
      profile-generate-mode: ${{ inputs.pgo }}

  part2:
    needs: [get-buildid, part1]
    if: ${{ inputs.pgo }}
    uses: ./.github/workflows/pgo-mac.yml

  part3:
    needs: [get-buildid, part1, part2]
    if: ${{ inputs.pgo }}
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      arch: x86_64
      debug: ${{ inputs.debug }}
      MOZ_BUILD_DATE: ${{ needs.get-buildid.outputs.buildids }}
      build-with-profdata-and-jarlog: true

  part2_no_pgo:
    name: "Integration (No PGO)"
    needs: [get-buildid, part1]
    if: ${{ !inputs.pgo }}
    uses: ./.github/workflows/mac_integration.yml
    secrets: inherit
    with:
      x86_64_artifact_name: noraneko-mac-x86_64-package
      aarch64_artifact_name: noraneko-mac-aarch64-package
      MOZ_BUILD_DATE: ${{ needs.get-buildid.outputs.buildids }}

  part4_pgo:
    name: "Integration (With PGO)"
    needs: [get-buildid, part1, part2, part3]
    if: ${{ inputs.pgo }}
    uses: ./.github/workflows/mac_integration.yml
    secrets: inherit
    with:
      x86_64_artifact_name: noraneko-mac-x86_64-package
      aarch64_artifact_name: noraneko-mac-aarch64-package
      MOZ_BUILD_DATE: ${{ needs.get-buildid.outputs.buildids }}
